"""Archived H100T7R-BS writable property constraints."""

from __future__ import annotations

from typing import Any

DRYER_CONTROL_SPECS: dict[str, dict[str, Any]] = {
    "washingTime": {"kind": "int", "minimum": 0, "maximum": 1440, "step": 1},
    "washShellWashingTime": {"kind": "int", "minimum": 0, "maximum": 1440, "step": 1},
    "powerSwitch": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "childLock": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "washShellMode": {
        "kind": "enum",
        "options": (
            (0, "混合"),
            (1, "快烘"),
            (2, "衬衫"),
            (4, "婴儿服"),
            (5, "羽绒"),
            (6, "棉麻"),
            (7, "羊毛"),
            (8, "真丝"),
            (10, "除菌螨"),
            (12, "大件"),
            (14, "空气洗"),
            (15, "热风清新"),
            (16, "童装"),
            (17, "内衣"),
            (18, "毛巾"),
            (19, "运动服"),
            (20, "冷风护理"),
            (21, "家纺"),
            (22, "冲锋衣"),
            (23, "轻柔"),
            (24, "化纤"),
            (25, "牛仔"),
            (26, "蚕丝被"),
            (27, "AI智慧烘"),
        ),
    },
    "washShellDryMode": {
        "kind": "enum",
        "options": ((0, "熨烫"), (1, "即穿"), (2, "储藏"), (3, "智能")),
    },
    "washShellWashingTemp": {"kind": "int", "minimum": 0, "maximum": 100, "step": 1},
    "lowerShellWashingTimeSet": {
        "kind": "enum",
        "options": (
            (1, "默认时间"),
            (3, "+10分钟"),
            (5, "+20分钟"),
            (7, "+30分钟"),
            (9, "+40分钟"),
            (11, "+50分钟"),
            (13, "+60分钟"),
            (15, "+70分钟"),
            (17, "+80分钟"),
            (19, "+90分钟"),
            (21, "+100分钟"),
            (23, "+110分钟"),
            (25, "+120分钟"),
            (27, "+130分钟"),
            (29, "+140分钟"),
            (31, "+150分钟"),
            (113, "-60分钟"),
            (125, "-120分钟"),
        ),
    },
    "creaseResistance": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "washMuteMode": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "speedUpMode": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "lowTempDry": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "dryWindSpeed": {
        "kind": "enum",
        "options": ((0, "智能"), (1, "柔风"), (2, "标准"), (3, "强劲")),
    },
    "washShellOrderTime": {"kind": "int", "minimum": 0, "maximum": 1440, "step": 1},
    "washShellOrderMode": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "uvSterilize": {"kind": "bool", "options": ((0, "关闭"), (1, "开启"))},
    "washShellRunStatus": {
        "kind": "enum",
        "options": ((0, "待机"), (1, "暂停"), (2, "运行")),
    },
    "lowerShellWashingStatus": {
        "kind": "enum",
        "options": (
            (0, "预约等待"),
            (1, "烘干"),
            (2, "已完成"),
            (3, "防皱"),
            (4, "数据同步中"),
            (5, "检测含水率"),
            (6, "AUTO"),
        ),
    },
    "collectionRun": {
        "kind": "enum",
        "options": (
            (0, "未运行收藏"),
            (1, "收藏1"),
            (2, "收藏2"),
            (3, "收藏3"),
            (4, "收藏4"),
            (5, "收藏5"),
        ),
    },
    "errorCode": {
        "kind": "array",
        "options": (
            (1, "dC 启动后，门未锁上"),
            (2, "E11 干衣机浮子开关导通异常"),
            (3, "E12 蒸汽护理发生器浮子开关异常"),
            (4, "E41 压缩机温度传感器故障"),
            (5, "E42 风道温度传感器故障"),
            (6, "E51 变频筒电机故障"),
            (7, "E52 变频压缩机故障"),
            (8, "E61 筒电机变频板故障"),
            (9, "E62 压缩机变频板故障"),
            (10, "E71 主、显板通讯故障"),
            (11, "E72 主板与筒电机变频通讯故障"),
            (12, "E73 主板与压缩机变频通讯故障"),
            (13, "E21 蒸汽发生器加热异常故障"),
            (14, "E43 整机前侧温度传感器故障"),
            (15, "E44 蒸汽发生器温度传感器故障"),
            (16, "Ful 排水浮子开关异常"),
        ),
        "size": 16,
    },
}
